---
apiVersion: v1
kind: Service
metadata:
  name: postgres-app-service
  labels:
    author: maruti
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: postgres-app
...
