---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: mydb
    author: maruti
spec:
  containers:
    - name: mysql-container
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: maruti
      volumeMounts:
      - name: myvolume
        mountPath: /var/lib/mysql
  volumes:
    - name: myvolume
      emptyDir: {}
...
