---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    name: result-app
    author: maruti
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30010
  selector:
    app: result-app    
...
      
