---
apiVersion: v1
kind: Service
metadata:
  name: service-pod
  labels:
    type: service
    author: maruti
spec:
  clusterIP: None
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    author: maruti
    app: db
spec:
  replicas: 2
  serviceName: mysql
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: mysql-pod
      labels:
        app: db
    spec:
      containers:
        - name: mysql-container
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: maruti
          volumeMounts:
            - name: mysql-volume 
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1G
...


