---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-role-binding
  namespace: test-ns
subjects:
  - kind: User
    name: raju
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
...

